name: GvApp
description: "A new Flutter project."
publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.0 
  url_launcher: ^6.0.20
  google_generative_ai: ^0.4.6
  speech_to_text: ^7.0.0
  permission_handler: ^11.2.1
  flutter_tts: ^3.3.0
  intl: ^0.17.0
  http: ^1.1.0
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.0
  #qr_code_scanner: ^1.0.1
  image_picker: ^1.1.1
  mobile_scanner: ^6.0.1
  sensors_plus: ^6.1.0
  local_auth: ^2.0.8
  google_mobile_ads: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/LOGO.png
    - assets/USER.jpg
    - assets/UP.jpg
    - assets/google.png
    - assets/facebook.png
    - assets/X.png
    - assets/Gladbox.png
    #- assets/profile_picture.png
    #- assets/post_image.png
